<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;Dk8AQn47eCl7ImA9Wx9WFkg.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/1231/comments/full/7</ns0:id><ns0:author>
			<ns0:name>bugdro...@chromium.org</ns0:name><ns0:uri>/u/101788990881243245974/</ns0:uri></ns0:author><ns0:content type="html">The following revision refers to this bug:
    http://src.chromium.org/viewvc/chrome?view=rev&amp;revision=4205

------------------------------------------------------------------------
r4205 | mseaborn@chromium.org | Fri Jan 21 16:02:55 PST 2011

Changed paths:
 M http://src.chromium.org/viewvc/chrome/trunk/src/native_client/tools/test_lib.py?r1=4205&amp;r2=4204&amp;pathrev=4205

Test runner: Work around bug in Linux's times() syscall interface

This bug has caused the toolchain builder to fail twice today.

BUG=http://code.google.com/p/nativeclient/issues/detail?id=1231
TEST=tested by manually inserting "raise OSError()"

Review URL: http://codereview.chromium.org/6278008
------------------------------------------------------------------------</ns0:content><ns0:updated>2011-01-22T00:07:23.000Z</ns0:updated><ns0:published>2011-01-22T00:07:23.000Z</ns0:published><ns2:updates /><ns0:title>Comment 7 by bugdro...@chromium.org</ns0:title><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=1231#c7" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/1231/comments/full/7" rel="self" type="application/atom+xml" /></ns0:entry>