<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;CUUMQX47eCl7ImA9WhVTEU0.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/full/2130</ns0:id><ns0:author>
			<ns0:name>mli...@google.com</ns0:name><ns0:uri>/u/109474787648168037085/</ns0:uri></ns0:author><ns0:content type="html">On the linux SDK builder, build can fail with an error.  The problem looks like it's caused by flakyness in the download toolchains script from the include native_client repo. 


&lt;b&gt;On what operating system?&lt;/b&gt;
Linux

&lt;b&gt;What steps will reproduce the problem?&lt;/b&gt;
1.  Commit a CL or look at this broken build attempt: http://build.chromium.org/p/client.nacl.sdk/builders/linux-sdk/builds/333/steps/update/logs/stdio
&lt;b&gt;2.&lt;/b&gt;
&lt;b&gt;3.&lt;/b&gt;

&lt;b&gt;What is the expected output? What do you see instead?&lt;/b&gt;

Expected: Build Success
Instead: Build Failure



&lt;b&gt;Please provide any additional information below and attach any relevant&lt;/b&gt;
&lt;b&gt;source files.&lt;/b&gt;

Here's the log


________ running '/usr/bin/python src/third_party/native_client/native_client/build/download_toolchains.py --x86-version 6191 --arm-version 6191' in '/mnt/data/b/build/slave/linux-sdk/build'

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
linux_x86: downloading version 6191...
linux_x86_newlib: downloading version 6191...
pnacl_linux_x86_64_newlib: downloading version 6191...
pnacl_linux_x86_64_glibc: downloading version 6191...
Traceback (most recent call last):
  File &amp;quot;src/third_party/native_client/native_client/build/download_toolchains.py&amp;quot;, line 83, in &amp;lt;module&amp;gt;
    Main()
  File &amp;quot;src/third_party/native_client/native_client/build/download_toolchains.py&amp;quot;, line 64, in Main
    sync_tgz.SyncTgz(url, dst, verbose=False)
  File &amp;quot;/mnt/data/b/build/slave/linux-sdk/build/src/third_party/native_client/native_client/build/sync_tgz.py&amp;quot;, line 102, in SyncTgz
    tgz_filename, '-C', target])
  File &amp;quot;/usr/lib/python2.6/subprocess.py&amp;quot;, line 498, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', '-xSzpf', 'src/third_party/native_client/native_client/toolchain/pnacl_linux_x86_64_glibc/.tgz', '-C', 'src/third_party/native_client/native_client/toolchain/pnacl_linux_x86_64_glibc']' returned non-zero exit status 2
Error: /usr/bin/python src/third_party/native_client/native_client/build/download_toolchains.py --x86-version 6191 --arm-version 6191 in /mnt/data/b/build/slave/linux-sdk/build returned 1
elapsedTime=236.366166
program finished with exit code 2
</ns0:content><ns0:updated>2012-02-24T17:08:00.000Z</ns0:updated><ns0:published>2011-08-03T15:12:12.000Z</ns0:published><ns2:status>Assigned</ns2:status><ns2:owner>
			<ns2:uri>/u/bradnelson@google.com/</ns2:uri><ns2:username>bradnelson@google.com</ns2:username></ns2:owner><ns2:cc>
			<ns2:uri>/u/mseaborn@chromium.org/</ns2:uri><ns2:username>mseaborn@chromium.org</ns2:username></ns2:cc><ns2:state>open</ns2:state><ns0:title>download toochains script seems to be flaky</ns0:title><ns2:label>Type-Defect</ns2:label><ns2:label>Pri-2</ns2:label><ns2:label>Component-Infrastructure</ns2:label><ns2:label>OS-Linux</ns2:label><ns2:label>Mstone-20</ns2:label><ns0:link href="http://code.google.com/feeds/issues/p/nativeclient/issues/2130/comments/full" rel="replies" type="application/atom+xml" /><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=2130" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/full/2130" rel="self" type="application/atom+xml" /><ns2:stars>1</ns2:stars><ns2:id>2130</ns2:id></ns0:entry>