<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;CEIDQ347eCl7ImA9WhJVEEo.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/2968/comments/full/5</ns0:id><ns0:author>
			<ns0:name>halya...@chromium.org</ns0:name><ns0:uri>/u/103196427465586990847/</ns0:uri></ns0:author><ns0:content type="html">I installed my hook library and found that python calls SetErrorMode(SEM_FAILCRITICALERRORS) in _PyImport_GetDynLoadFunc function in Python-2.6\Python\dynload_win.c. This is what messes with our SetErrorMode calls. shortname parameter passed to this function is "_ctypes" (I haven't checked that _ctypes.pyd is the only dll that interferes). So one of the ways to solve this problem is to load all DLLs that python needs before running our tests.</ns0:content><ns0:updated>2012-08-27T13:02:52.000Z</ns0:updated><ns0:published>2012-08-27T13:02:52.000Z</ns0:published><ns2:updates /><ns0:title>Comment 5 by halya...@chromium.org</ns0:title><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=2968#c5" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/2968/comments/full/5" rel="self" type="application/atom+xml" /></ns0:entry>