<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;DUUMQX47eCl7ImA9WhdWEk4.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/full/2025</ns0:id><ns0:author>
			<ns0:name>pol...@google.com</ns0:name><ns0:uri>/u/101953680983947802512/</ns0:uri></ns0:author><ns0:content type="html">TestOpen releases PPB_FileSystem resource right after invoking Open. As a result, Open() on the browser side is aborted before it completed the operation, so OpenCallback is called with result=PP_ERROR_ABORTED. We therefore have no way of confirming that we correctly passed function arguments via the proxy.

Instead OpenCallback should get the resource as user_data and release it.
It should CHECK that result is PP_OK.
</ns0:content><ns0:updated>2011-09-05T15:41:20.000Z</ns0:updated><ns0:published>2011-07-14T03:03:44.000Z</ns0:published><ns2:status>Fixed</ns2:status><ns2:owner>
			<ns2:uri>/u/111227428049549265840/</ns2:uri><ns2:username>sa...@google.com</ns2:username></ns2:owner><ns2:state>closed</ns2:state><ns0:title>ppapi_ppb_file_system_browser test must test completion of asynchronous Open operation</ns0:title><ns2:label>Type-Defect</ns2:label><ns2:label>Mstone-15</ns2:label><ns2:label>Pri-1</ns2:label><ns2:label>Component-Pepper</ns2:label><ns2:label>OS-</ns2:label><ns2:label>Arch-</ns2:label><ns0:link href="http://code.google.com/feeds/issues/p/nativeclient/issues/2025/comments/full" rel="replies" type="application/atom+xml" /><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=2025" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/full/2025" rel="self" type="application/atom+xml" /><ns2:stars>1</ns2:stars><ns2:closedDate>2011-09-01T22:00:08.000Z</ns2:closedDate><ns2:id>2025</ns2:id></ns0:entry>