<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;CE8NRH47eCl7ImA9WhZXEE4.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/1745/comments/full/1</ns0:id><ns0:author>
			<ns0:name>bugdro...@chromium.org</ns0:name><ns0:uri>/u/101788990881243245974/</ns0:uri></ns0:author><ns0:content type="html">The following revision refers to this bug:
    http://src.chromium.org/viewvc/chrome?view=rev&amp;revision=5093

------------------------------------------------------------------------
r5093 | mseaborn@chromium.org | Thu Apr 28 16:16:47 PDT 2011

Changed paths:
 M http://src.chromium.org/viewvc/chrome/trunk/src/native_client/build/sync_tgz.py?r1=5093&amp;r2=5092&amp;pathrev=5093

Toolchain downloader: Check for errors from subprocesses

Fix code which failed to check for failures from os.spawnve() calls.
Use subprocess.check_call() instead.

Note that this means we don't need strange double-quoting when passing
commands to Bash, since 'subprocess' handles this correctly.

Add a comment to the obscure symlink-munging code.

BUG=http://code.google.com/p/nativeclient/issues/detail?id=1745
TEST=run on trybots with "continue" commented out in download_toolchains.py
  to force the downloads to run

Review URL: http://codereview.chromium.org/6903122
------------------------------------------------------------------------</ns0:content><ns0:updated>2011-04-28T23:21:35.000Z</ns0:updated><ns0:published>2011-04-28T23:21:35.000Z</ns0:published><ns2:updates /><ns0:title>Comment 1 by bugdro...@chromium.org</ns0:title><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=1745#c1" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/1745/comments/full/1" rel="self" type="application/atom+xml" /></ns0:entry>