<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;AkMHSH47eCl7ImA9WhNSEkQ.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/3086/comments/full/10</ns0:id><ns0:author>
			<ns0:name>bugdro...@chromium.org</ns0:name><ns0:uri>/u/101788990881243245974/</ns0:uri></ns0:author><ns0:content type="html">The following revision refers to this bug:
    http://src.chromium.org/viewvc/native_client?view=rev&amp;revision=10114

------------------------------------------------------------------------
r10114 | bradnelson@google.com | 2012-10-27T00:36:15.348599Z

Changed paths:
   M http://src.chromium.org/viewvc/native_client/trunk/src/native_client/toolchain_build/once_test.py?r1=10114&amp;r2=10113&amp;pathrev=10114
   M http://src.chromium.org/viewvc/native_client/trunk/src/native_client/toolchain_build/once.py?r1=10114&amp;r2=10113&amp;pathrev=10114
   M http://src.chromium.org/viewvc/native_client/trunk/src/native_client/toolchain_build/toolchain_main.py?r1=10114&amp;r2=10113&amp;pathrev=10114

Make the bots fail if they can't cache build results.

We had been ignoring write failures to the datastore.
This is not the right behavior for the bots (only locally).

BUG=http://code.google.com/p/nativeclient/issues/detail?id=3086
TEST=once_test.py
R=ncbray@google.com

Review URL: https://codereview.chromium.org/11311020
------------------------------------------------------------------------</ns0:content><ns0:updated>2012-10-27T00:40:39.000Z</ns0:updated><ns0:published>2012-10-27T00:40:39.000Z</ns0:published><ns2:updates /><ns0:title>Comment 10 by bugdro...@chromium.org</ns0:title><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=3086#c10" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/3086/comments/full/10" rel="self" type="application/atom+xml" /></ns0:entry>