<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;C0AMQX47eCl7ImA9WhVVEU8.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/full/1983</ns0:id><ns0:author>
			<ns0:name>noelal...@google.com</ns0:name><ns0:uri>/u/113000403807150741221/</ns0:uri></ns0:author><ns0:content type="html">We see two failures in the coverage test, where the command loader is reporting a failed test, but the output from the test, shows the expected value was returned.  

This happened on a CL which appeared to have no effect on either they python test runner or the nexe.

http://chromegw.corp.google.com/i/client.nacl/builders/lucid-64-32-newlib-coverage/builds/609

/usr/bin/python tools/command_tester.py --name /mnt/data/b/build/slave/lucid-64-32-newlib-coverage/build/native_client/scons-out/nacl-x86-32/test_results/crash_in_syscall_test.out --report /mnt/data/b/build/slave/lucid-64-32-newlib-coverage/build/native_client/scons-out/nacl-x86-32/test_results/crash_in_syscall_test.out --time_warning 10 --time_error 100 --perf_env_description x86-32_nnacl_newlib_static_irt --using_nacl_signal_handler 1 --subarch 32 --arch x86 --exit_status trusted_segfault scons-out/coverage-linux-x86-32/staging/sel_ldr -S -- scons-out/nacl-x86-32/obj/tests/signal_handler/crash_in_syscall.nexe
======================================================================
running ['scons-out/coverage-linux-x86-32/staging/sel_ldr', '-S', '--', 'scons-out/nacl-x86-32/obj/tests/signal_handler/crash_in_syscall.nexe']
======================================================================
scons-out/coverage-linux-x86-32/staging/sel_ldr -S -- scons-out/nacl-x86-32/obj/tests/signal_handler/crash_in_syscall.nexe
Test /mnt/data/b/build/slave/lucid-64-32-newlib-coverage/build/native_client/scons-out/nacl-x86-32/test_results/crash_in_syscall_test.out took 0.020000 secs

ERROR: Command returned exit status -11 (0xfffffff5) but we expected 245 (0xf5)
======================================================================
Stdout
======================================================================

======================================================================
Stderr
======================================================================

** Signal 11 from trusted code: Halting at 8057DA9h

crash_in_syscall_test.out: FAILED
scons: *** [scons-out/nacl-x86-32/test_results/crash_in_syscall_test.out] Error 255
</ns0:content><ns0:updated>2012-05-04T08:56:20.000Z</ns0:updated><ns0:published>2011-07-07T16:51:16.000Z</ns0:published><ns2:status>Available</ns2:status><ns2:cc>
			<ns2:uri>/u/100032148147647801554/</ns2:uri><ns2:username>ncb...@google.com</ns2:username></ns2:cc><ns2:state>open</ns2:state><ns0:title>Flaky signal on Coverage bot.</ns0:title><ns2:label>Type-Defect</ns2:label><ns2:label>Mstone-X</ns2:label><ns2:label>Pri-2</ns2:label><ns2:label>Component-Infrastructure</ns2:label><ns2:label>OS-</ns2:label><ns2:label>Arch-</ns2:label><ns0:link href="http://code.google.com/feeds/issues/p/nativeclient/issues/1983/comments/full" rel="replies" type="application/atom+xml" /><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=1983" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/full/1983" rel="self" type="application/atom+xml" /><ns2:stars>1</ns2:stars><ns2:id>1983</ns2:id></ns0:entry>