<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.google.com/g/2005" xmlns:ns2="http://schemas.google.com/projecthosting/issues/2009" ns1:etag="W/&quot;D0QDRX47eCl7ImA9WhZVGEo.&quot;">
		<ns0:id>http://code.google.com/feeds/issues/p/nativeclient/issues/1462/comments/full/4</ns0:id><ns0:author>
			<ns0:name>bugdro...@chromium.org</ns0:name><ns0:uri>/u/101788990881243245974/</ns0:uri></ns0:author><ns0:content type="html">The following revision refers to this bug:
    http://src.chromium.org/viewvc/chrome?view=rev&amp;revision=5514

------------------------------------------------------------------------
r5514 | mseaborn@chromium.org | Tue May 31 13:51:01 PDT 2011

Changed paths:
 M http://src.chromium.org/viewvc/chrome/trunk/src/native_client/src/trusted/python_bindings/test_python_imc.py?r1=5514&amp;r2=5513&amp;pathrev=5514

Disable test_send_error in the Python IMC tests on Mac OS X

This test occasionally fails on Mac.

BUG=http://code.google.com/p/nativeclient/issues/detail?id=1462
TEST=run_python_imc_test

Review URL: http://codereview.chromium.org/7002037
------------------------------------------------------------------------</ns0:content><ns0:updated>2011-05-31T20:56:14.000Z</ns0:updated><ns0:published>2011-05-31T20:56:14.000Z</ns0:published><ns2:updates /><ns0:title>Comment 4 by bugdro...@chromium.org</ns0:title><ns0:link href="http://code.google.com/p/nativeclient/issues/detail?id=1462#c4" rel="alternate" type="text/html" /><ns0:link href="https://code.google.com/feeds/issues/p/nativeclient/issues/1462/comments/full/4" rel="self" type="application/atom+xml" /></ns0:entry>